# Generated by Django 3.2.3 on 2021-05-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='district',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.district'),
        ),
    ]
