# Generated by Django 3.2.3 on 2021-05-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_state_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.district'),
        ),
    ]
