# Generated by Django 3.2.3 on 2021-05-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20210525_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='telegram',
        ),
    ]
